In [2]:
import pandas as pd

df = pd.read_excel('data.xlsx', index_col=0)

In [3]:
print(df)

    Annotater     video id  Attractive Level (1-5)  Question 2: Sound (1-5)  \
1    nghiatnh  5OzrpNCyXqs                       5                        5
2     hoangnd  5OzrpNCyXqs                       5                        5
3        hanl  5OzrpNCyXqs                       5                        5
9    nghiatnh  3qfTtx3yG5U                       3                        3
10    hoangnd  3qfTtx3yG5U                       2                        2
..        ...          ...                     ...                      ...
206   Group 2  Aww_IL-0-C8                       4                        4
207   Group 3  Aww_IL-0-C8                       5                        5
208   Group 1  eZyK0ED21vI                       2                        3
209   Group 2  eZyK0ED21vI                       2                        2
210   Group 3  eZyK0ED21vI                       3                        3

     Question 2.1: Music (1-5)  Question 2.2 : Noise control (1-5)  \
1                            4                                   5
2                            5                                   5
3                            5                                   5
9                            4                                   3
10                           2                                   2
..                         ...                                 ...
206                          4                                   4
207                          5                                   4
208                          2                                   2
209                          4                                   3
210                          4                                   3

     Question 2.3 : Speaking Style (1-5)  Question 3: Camera (1-5)  \
1                                      5                         5
2                                      4                         5
3                                      5                         5
9                                      2                         3
10                                     3                         4
..                                   ...                       ...
206                                    5                         4
207                                    5                         5
208                                    2                         2
209                                    2                         2
210                                    3                         4

     Question 3.1: Stable (1-5)  Question 3.2: Angel diversity (0-1)  \
1                             5                                    1
2                             5                                    1
3                             5                                    1
9                             5                                    0
10                            5                                    0
..                          ...                                  ...
206                           4                                    1
207                           5                                    1
208                           3                                    0
209                           3                                    1
210                           4                                    1

     Question 4: Images (1-5)  Question 4.1: Resolution (1-5)  \
1                           5                               5
2                           5                               5
3                           5                               5
9                           3                               4
10                          3                               4
..                        ...                             ...
206                         5                               4
207                         5                               4
208                         2                               3
209                         2                               3
210                         4                               3

     Question 4.2: Color (1-5)  Question 5: Content (1-5)  \
1                            5                          5
2                            5                          5
3                            5                          5
9                            3                          1
10                           3                          2
..                         ...                        ...
206                          5                          5
207                          5                          5
208                          2                          2
209                          2                          3
210                          3                          4

     Question 5.1: Introduction (0-1)  Question 5.2: Food description (0-1)  \
1                                   1                                     1
2                                   1                                     1
3                                   1                                     1
9                                   0                                     1
10                                  1                                     0
..                                ...                                   ...
206                                 1                                     1
207                                 1                                     1
208                                 1                                     1
209                                 1                                     0
210                                 1                                     1

     Question 6: Reviewer (1-5)  \
1                             5
2                             5
3                             5
9                             2
10                            2
..                          ...
206                           5
207                           5
208                           3
209                           3
210                           3

     Question 6.1: Reviewer emotion is negative - neutral - positive (1-3)  \
1                                                    3
2                                                    3
3                                                    2
9                                                    2
10                                                   2
..                                                 ...
206                                                  3
207                                                  3
208                                                  3
209                                                  2
210                                                  2

     Question 6.2: Recommendation (0-1)  Question 6.3: Clear information (0-1)
1                                     0                                      1
2                                     0                                      1
3                                     0                                      1
9                                     0                                      0
10                                    0                                      0
..                                  ...                                    ...
206                                   0                                      1
207                                   0                                      1
208                                   0                                      0
209                                   0                                      1
210                                   0                                      1

[405 rows x 20 columns]

In [4]:
print(df.columns)

Index(['Annotater', 'video id', 'Attractive Level (1-5)',
       'Question 2: Sound (1-5)', 'Question 2.1: Music (1-5)',
       'Question 2.2 : Noise control (1-5)',
       'Question 2.3 : Speaking Style (1-5)', 'Question 3: Camera (1-5)',
       'Question 3.1: Stable (1-5)', 'Question 3.2: Angel diversity (0-1)',
       'Question 4: Images (1-5)', 'Question 4.1: Resolution (1-5)',
       'Question 4.2: Color (1-5)', 'Question 5: Content (1-5)',
       'Question 5.1: Introduction (0-1)',
       'Question 5.2: Food description (0-1)', 'Question 6: Reviewer (1-5)',
       'Question 6.1: Reviewer emotion is negative - neutral - positive (1-3)',
       'Question 6.2: Recommendation (0-1)',
       'Question 6.3: Clear information (0-1)'],
      dtype='object')

In [5]:
complete_df = df[~pd.isna(df).any(axis=1)].reset_index(drop=True)
complete_df

,Annotater,video id,Attractive Level (1-5),Question 2: Sound (1-5),Question 2.1: Music (1-5),Question 2.2 : Noise control (1-5),Question 2.3 : Speaking Style (1-5),Question 3: Camera (1-5),Question 3.1: Stable (1-5),Question 3.2: Angel diversity (0-1),Question 4: Images (1-5),Question 4.1: Resolution (1-5),Question 4.2: Color (1-5),Question 5: Content (1-5),Question 5.1: Introduction (0-1),Question 5.2: Food description (0-1),Question 6: Reviewer (1-5),Question 6.1: Reviewer emotion is negative - neutral - positive (1-3),Question 6.2: Recommendation (0-1),Question 6.3: Clear information (0-1)
0,nghiatnh,5OzrpNCyXqs,5,5,4,5,5,5,5,1,5,5,5,5,1,1,5,3,0,1
1,hoangnd,5OzrpNCyXqs,5,5,5,5,4,5,5,1,5,5,5,5,1,1,5,3,0,1
2,hanl,5OzrpNCyXqs,5,5,5,5,5,5,5,1,5,5,5,5,1,1,5,2,0,1
3,nghiatnh,3qfTtx3yG5U,3,3,4,3,2,3,5,0,3,4,3,1,0,1,2,2,0,0
4,hoangnd,3qfTtx3yG5U,2,2,2,2,3,4,5,0,3,4,3,2,1,0,2,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
400,Group 2,Aww_IL-0-C8,4,4,4,4,5,4,4,1,5,4,5,5,1,1,5,3,0,1
401,Group 3,Aww_IL-0-C8,5,5,5,4,5,5,5,1,5,4,5,5,1,1,5,3,0,1
402,Group 1,eZyK0ED21vI,2,3,2,2,2,2,3,0,2,3,2,2,1,1,3,3,0,0
403,Group 2,eZyK0ED21vI,2,2,4,3,2,2,3,1,2,3,2,3,1,0,3,2,0,1
404,Group 3,eZyK0ED21vI,3,3,4,3,3,4,4,1,4,3,3,4,1,1,3,2,0,1

In [6]:
from asyncio.windows_events import NULL
from cmath import nan


count = 1
l = len(complete_df['video id'])
x = complete_df['video id'][0]
count = 1
for i in range(1, l):
    if complete_df['video id'][i] == x:
        count += 1
    else:
        x = complete_df['video id'][i]
        if count == 3:
            complete_df['video id'][i-1] = nan
            complete_df['video id'][i-2] = nan
            complete_df['video id'][i-3] = nan
        count = 1

C:\Users\Admin\AppData\Local\Temp\ipykernel_1208\340407739.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  complete_df['video id'][i-1] = nan
C:\Users\Admin\AppData\Local\Temp\ipykernel_1208\340407739.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  complete_df['video id'][i-2] = nan
C:\Users\Admin\AppData\Local\Temp\ipykernel_1208\340407739.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  complete_df['video id'][i-3] = nan

In [7]:
complete_df

,Annotater,video id,Attractive Level (1-5),Question 2: Sound (1-5),Question 2.1: Music (1-5),Question 2.2 : Noise control (1-5),Question 2.3 : Speaking Style (1-5),Question 3: Camera (1-5),Question 3.1: Stable (1-5),Question 3.2: Angel diversity (0-1),Question 4: Images (1-5),Question 4.1: Resolution (1-5),Question 4.2: Color (1-5),Question 5: Content (1-5),Question 5.1: Introduction (0-1),Question 5.2: Food description (0-1),Question 6: Reviewer (1-5),Question 6.1: Reviewer emotion is negative - neutral - positive (1-3),Question 6.2: Recommendation (0-1),Question 6.3: Clear information (0-1)
0,nghiatnh,NaN,5,5,4,5,5,5,5,1,5,5,5,5,1,1,5,3,0,1
1,hoangnd,NaN,5,5,5,5,4,5,5,1,5,5,5,5,1,1,5,3,0,1
2,hanl,NaN,5,5,5,5,5,5,5,1,5,5,5,5,1,1,5,2,0,1
3,nghiatnh,NaN,3,3,4,3,2,3,5,0,3,4,3,1,0,1,2,2,0,0
4,hoangnd,NaN,2,2,2,2,3,4,5,0,3,4,3,2,1,0,2,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
400,Group 2,NaN,4,4,4,4,5,4,4,1,5,4,5,5,1,1,5,3,0,1
401,Group 3,NaN,5,5,5,4,5,5,5,1,5,4,5,5,1,1,5,3,0,1
402,Group 1,eZyK0ED21vI,2,3,2,2,2,2,3,0,2,3,2,2,1,1,3,3,0,0
403,Group 2,eZyK0ED21vI,2,2,4,3,2,2,3,1,2,3,2,3,1,0,3,2,0,1
404,Group 3,eZyK0ED21vI,3,3,4,3,3,4,4,1,4,3,3,4,1,1,3,2,0,1

In [8]:
result = complete_df[~pd.isna(complete_df).any(axis=1)].reset_index(drop=True)
result

,Annotater,video id,Attractive Level (1-5),Question 2: Sound (1-5),Question 2.1: Music (1-5),Question 2.2 : Noise control (1-5),Question 2.3 : Speaking Style (1-5),Question 3: Camera (1-5),Question 3.1: Stable (1-5),Question 3.2: Angel diversity (0-1),Question 4: Images (1-5),Question 4.1: Resolution (1-5),Question 4.2: Color (1-5),Question 5: Content (1-5),Question 5.1: Introduction (0-1),Question 5.2: Food description (0-1),Question 6: Reviewer (1-5),Question 6.1: Reviewer emotion is negative - neutral - positive (1-3),Question 6.2: Recommendation (0-1),Question 6.3: Clear information (0-1)
0,Group 1,eZyK0ED21vI,2,3,2,2,2,2,3,0,2,3,2,2,1,1,3,3,0,0
1,Group 2,eZyK0ED21vI,2,2,4,3,2,2,3,1,2,3,2,3,1,0,3,2,0,1
2,Group 3,eZyK0ED21vI,3,3,4,3,3,4,4,1,4,3,3,4,1,1,3,2,0,1

In [9]:
result.to_csv('result.csv')