In [26]:
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.metrics import f1_score
import numpy as np
import math

In [27]:
df = pd.read_excel('median_data.xlsx', index_col=0)

In [28]:
df

,video id,Question 2: Sound (1-5),Question 2.1: Music (1-5),Question 2.2 : Noise control (1-5),Question 2.3 : Speaking Style (1-5),Question 3: Camera (1-5),Question 3.1: Stable (1-5),Question 3.2: Angel diversity (0-1),Question 4: Images (1-5),Question 4.1: Resolution (1-5),Question 4.2: Color (1-5),Question 5: Content (1-5),Question 5.1: Introduction (0-1),Question 5.2: Food description (0-1),Question 6: Reviewer (1-5),Question 6.1: Reviewer emotion is negative - neutral - positive (1-3),Question 6.2: Recommendation (0-1),Question 6.3: Clear information (0-1),Attractive Level (1-5)
0,mSg4AmqvT0I,4,4,4,4,4,4,1,5,4,5,4,1,1,3,2,0,1,3
1,Lol8sqRfQYE,3,3,1,3,3,3,1,3,3,3,3,1,1,3,3,1,1,2
2,kwwGvRUyIG8,4,3,2,3,4,4,1,4,5,4,4,1,1,4,3,1,1,4
3,52alUCchcBw,2,3,1,3,3,3,1,2,4,1,3,1,0,2,2,0,1,2
4,iDCC0SEHDY8,4,4,2,3,2,4,0,3,4,2,3,1,0,3,2,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,Yr9Z19ZWMfg,4,4,3,4,4,3,1,4,4,4,5,1,1,4,3,1,1,4
131,umhYUSmtkIw,3,3,3,3,3,4,1,3,4,3,3,1,1,4,2,0,1,3
132,7JsskyOhp0I,4,4,2,4,4,4,1,4,4,4,5,1,1,4,3,1,1,4
133,usrgPQ74WVA,3,3,3,3,3,3,1,3,4,3,3,1,1,4,2,0,1,2
134,eZCiJihCPUE,5,5,4,5,5,5,1,4,4,4,5,1,1,5,3,1,1,4

In [29]:
df.columns

Index(['video id', 'Question 2: Sound (1-5)', 'Question 2.1: Music (1-5)',
       'Question 2.2 : Noise control (1-5)',
       'Question 2.3 : Speaking Style (1-5)', 'Question 3: Camera (1-5)',
       'Question 3.1: Stable (1-5)', 'Question 3.2: Angel diversity (0-1)',
       'Question 4: Images (1-5)', 'Question 4.1: Resolution (1-5)',
       'Question 4.2: Color (1-5)', 'Question 5: Content (1-5)',
       'Question 5.1: Introduction (0-1)',
       'Question 5.2: Food description (0-1)', 'Question 6: Reviewer (1-5)',
       'Question 6.1: Reviewer emotion is negative - neutral - positive (1-3)',
       'Question 6.2: Recommendation (0-1)',
       'Question 6.3: Clear information (0-1)', 'Attractive Level (1-5)'],
      dtype='object')

In [30]:
len(df)

135

In [31]:
input_columns = [
       'Question 2: Sound (1-5)', 'Question 2.1: Music (1-5)','Question 2.2 : Noise control (1-5)','Question 2.3 : Speaking Style (1-5)', 
       'Question 3: Camera (1-5)','Question 3.1: Stable (1-5)', 'Question 3.2: Angel diversity (0-1)',
       'Question 4: Images (1-5)', 'Question 4.1: Resolution (1-5)', 'Question 4.2: Color (1-5)', 
       'Question 5: Content (1-5)', 'Question 5.1: Introduction (0-1)', 'Question 5.2: Food description (0-1)', 'Question 6: Reviewer (1-5)',
       'Question 6.1: Reviewer emotion is negative - neutral - positive (1-3)', 'Question 6.2: Recommendation (0-1)', 'Question 6.3: Clear information (0-1)'
       ]
main_columns = [
        'Question 2: Sound (1-5)',
        'Question 3: Camera (1-5)',
        'Question 4: Images (1-5)', 
        'Question 5: Content (1-5)',
        'Question 6: Reviewer (1-5)'
       ]
output_column = 'Attractive Level (1-5)'

In [32]:
change_columns = [
        'Question 2: Sound (1-5)', 'Question 2.1: Music (1-5)','Question 2.2 : Noise control (1-5)','Question 2.3 : Speaking Style (1-5)', 
       'Question 3: Camera (1-5)','Question 3.1: Stable (1-5)',
       'Question 4: Images (1-5)', 'Question 4.1: Resolution (1-5)', 'Question 4.2: Color (1-5)', 
       'Question 5: Content (1-5)', 'Question 6: Reviewer (1-5)',
       'Question 6.1: Reviewer emotion is negative - neutral - positive (1-3)', 'Attractive Level (1-5)'
]

In [33]:
for i in change_columns:
    for j in range(len(df)):
        if int(df[i][j]) >= 3:
            df[i][j] = 1
        else:
            df[i][j] = 0

C:\Users\Admin\AppData\Local\Temp\ipykernel_12420\4058375588.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i][j] = 1
C:\Users\Admin\AppData\Local\Temp\ipykernel_12420\4058375588.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i][j] = 0

In [34]:
df

,video id,Question 2: Sound (1-5),Question 2.1: Music (1-5),Question 2.2 : Noise control (1-5),Question 2.3 : Speaking Style (1-5),Question 3: Camera (1-5),Question 3.1: Stable (1-5),Question 3.2: Angel diversity (0-1),Question 4: Images (1-5),Question 4.1: Resolution (1-5),Question 4.2: Color (1-5),Question 5: Content (1-5),Question 5.1: Introduction (0-1),Question 5.2: Food description (0-1),Question 6: Reviewer (1-5),Question 6.1: Reviewer emotion is negative - neutral - positive (1-3),Question 6.2: Recommendation (0-1),Question 6.3: Clear information (0-1),Attractive Level (1-5)
0,mSg4AmqvT0I,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1
1,Lol8sqRfQYE,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
2,kwwGvRUyIG8,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
3,52alUCchcBw,0,1,0,1,1,1,1,0,1,0,1,1,0,0,0,0,1,0
4,iDCC0SEHDY8,1,1,0,1,0,1,0,1,1,0,1,1,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,Yr9Z19ZWMfg,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
131,umhYUSmtkIw,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1
132,7JsskyOhp0I,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
133,usrgPQ74WVA,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,0
134,eZCiJihCPUE,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [35]:
X_train, X_test, y_train, y_test = train_test_split(df[input_columns][:], df[output_column][:], test_size=0.2, shuffle=True)

In [36]:
print(X_train.shape)
print(X_test.shape)

(108, 17)
(27, 17)

In [37]:
#create array of input
input_train = []*len(X_train)
for i in range(0, len(X_train)):
    y = []
    for j in X_train.iloc[i]:
        y.append(int(j))
    input_train.append(y)

In [38]:
#create array of output
output_train = []*len(y_train)
for i in range(0, len(y_train)):
    output_train.append([int(y_train.iloc[i])])

In [39]:
i_train = np.array(input_train)
o_train = np.array(output_train)

In [40]:
i_train

array([[1, 1, 0, ..., 0, 0, 1],
       [1, 1, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [1, 1, 1, ..., 1, 0, 1],
       [1, 1, 1, ..., 1, 0, 1],
       [1, 1, 1, ..., 0, 1, 1]])

In [41]:
def sigmod(x):
    return 1/(1 + np.exp(-float(x)))

def sigmod_cal(h):
    z = []*len(h)
    for i in range(len(h)):
        z.append([sigmod(int(h[i]))])
    return np.array(z, dtype=float)

In [42]:
def hypothesis(X, theta): 
    return np.dot(X, theta) 

def gradient(x, y, theta): 
    h = hypothesis(x, theta)
    z = sigmod_cal(h)
    grad = x.T.dot(z - y)
    return grad 
  

def loss(X, y, theta, m):
    z = sigmod_cal(hypothesis(X, theta))
    loss_value = -np.sum(y*np.log(z) + (1-y)*np.log(1-z))
    return float(loss_value)

In [43]:
def gradientDescent(x, y, learning_rate = 0.001): 
    theta = np.array([[1]]*x.shape[1]) 
    count = 0

    while True:
        l_old = loss(x, y , theta, x.shape[0])
        theta = theta + learning_rate * gradient(x, y, theta)
        l_new = loss(x, y , theta, x.shape[0])
        count += 1
        if count == 100:
            break
    return theta

In [44]:
theta = np.array([[1]]*i_train.shape[1])
h = hypothesis(i_train, theta)
z = sigmod_cal(h)

In [45]:
theta = gradientDescent(i_train, o_train)

C:\Users\Admin\AppData\Local\Temp\ipykernel_12420\1037673428.py:13: RuntimeWarning: divide by zero encountered in log
  loss_value = -np.sum(y*np.log(z) + (1-y)*np.log(1-z))
C:\Users\Admin\AppData\Local\Temp\ipykernel_12420\1037673428.py:13: RuntimeWarning: invalid value encountered in multiply
  loss_value = -np.sum(y*np.log(z) + (1-y)*np.log(1-z))

In [46]:
theta

array([[2.49997083],
       [2.29998438],
       [2.19877122],
       [3.29874332],
       [2.49873052],
       [3.39748933],
       [2.49997753],
       [3.19854217],
       [3.89624384],
       [2.7997651 ],
       [2.69996218],
       [2.59997725],
       [1.89996665],
       [2.19986256],
       [1.59998041],
       [1.19999833],
       [2.1998463 ]])

In [47]:
input_test = []*len(X_test)
for i in range(0, len(X_test)):
    y = []
    for j in X_test.iloc[i]:
        y.append(int(j))
    input_test.append(y)
i_test = np.array(input_test)

In [48]:
output_test = []*len(y_test)
for i in range(0, len(y_test)):
    output_test.append([int(y_test.iloc[i])])

In [49]:
o_test = np.array(output_test)

In [50]:
r_test = []*len(o_test)
for i in range(len(o_test)):
    r_test.append([math.floor(sigmod(i_test[i].dot(theta)))])
r_test = np.array(r_test)
test_df = pd.DataFrame({
    'Y_test' : o_test[:, 0],
    'Y_predict' : r_test[:, 0]
})

In [51]:
test_df

    Y_test  Y_predict
0        1          1
1        1          1
2        1          0
3        1          1
4        0          0
5        0          0
6        1          1
7        1          1
8        1          1
9        1          1
10       1          1
11       1          1
12       0          0
13       0          0
14       1          1
15       1          0
16       1          0
17       0          0
18       1          1
19       1          1
20       1          0
21       0          1
22       0          1
23       1          1
24       1          1
25       0          0
26       1          1

In [52]:
r_train = []*len(o_train)
for i in range(len(o_train)):
    r_train.append([math.floor(sigmod(i_train[i].dot(theta)))])
r_train = np.array(r_train)
print('Train accuracy: ', f1_score(r_train, y_train, average='macro'))
print('Test accuracy: ', f1_score(r_test, y_test, average='macro'))

Train accuracy:  0.7704887739074193
Test accuracy:  0.7499999999999999